# Generated by Django 3.2.9 on 2022-11-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Метка', 'verbose_name_plural': 'Метки'},
        ),
        migrations.AlterModelOptions(
            name='tagmatch',
            options={'verbose_name': 'Совпадение метки', 'verbose_name_plural': 'Совпадения меток'},
        ),
        migrations.AlterModelOptions(
            name='tagoption',
            options={'verbose_name': 'Вариант метки', 'verbose_name_plural': 'Варианты меток'},
        ),
        migrations.AlterField(
            model_name='tagoption',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
