# Generated by Django 3.2.9 on 2022-12-18 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20221125_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagoption',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tags.tag', verbose_name='Метка'),
        ),
    ]
