# Generated by Django 3.2.6 on 2021-08-29 13:16

import mptt.fields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('slug', core.fields.AutoSlugField(populate_from='name', unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка на страницу курса')),
                ('affiliate_url', models.URLField(blank=True, null=True, verbose_name='Партнёрская ссылка')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Онлайн'), (2, 'Оффлайн')], default=1, verbose_name='Тип')),
                ('difficulty', models.PositiveIntegerField(choices=[(1, 'С нуля'), (2, 'Продвинутый')], default=1, verbose_name='Уровень сложности')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена ₽')),
                ('price_category', models.PositiveIntegerField(choices=[(1, 'Бесплатно'), (2, 'Низкая цена'), (3, 'Средняя цена'), (4, 'Высокая цена')], default=3, verbose_name='Категория цены')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность курсов')),
                ('duration_type', models.PositiveSmallIntegerField(choices=[(1, 'Месяц'), (2, 'Урок')], default=1, verbose_name='Единицы измерения длительности курсов')),
                ('duration_category', models.PositiveIntegerField(choices=[(1, 'Короткая продолжительность'), (2, 'Средняя продолжительность'), (3, 'Высокая продолжительность')], default=2, verbose_name='Категория продолжительности')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован')], default=1, verbose_name='Статус')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала курсов')),
                ('installment', models.BooleanField(default=False, verbose_name='Возможна рассрочка')),
                ('course_format', models.CharField(default='Комбинированный', max_length=255, verbose_name='Формат проведения занятий')),
                ('deferred_payment', models.BooleanField(default=False, verbose_name='Возможен отложенный платёж')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновлёния')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.category')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'db_table': 'course_category',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(through='courses.CourseCategory', to='courses.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school', verbose_name='Школа'),
        ),
        migrations.CreateModel(
            name='CategoryAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255, unique=True, verbose_name='Псевдоним категории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.category', verbose_name='категория')),
            ],
        ),
    ]
