# Generated by Django 3.2.6 on 2021-08-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_category',
            field=models.PositiveIntegerField(choices=[(1, 'Короткая продолжительность'), (2, 'Небольшая продолжительность'), (3, 'Средняя продолжительность'), (4, 'Значительная продолжительность'), (5, 'Высокая продолжительность')], default=3, verbose_name='Категория продолжительности'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_category',
            field=models.PositiveIntegerField(choices=[(0, 'Бесплатно'), (1, 'Низкая цена'), (2, 'Невысокая цена'), (3, 'Средняя цена'), (4, 'Значительная цена'), (5, 'Высокая цена')], default=3, verbose_name='Категория цены'),
        ),
    ]
