# Generated by Django 3.2.2 on 2021-06-05 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='advantages',
        ),
        migrations.RemoveField(
            model_name='course',
            name='employment_assistance',
        ),
        migrations.RemoveField(
            model_name='course',
            name='learning_outcomes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='learning_process',
        ),
        migrations.RemoveField(
            model_name='course',
            name='support',
        ),
        migrations.RemoveField(
            model_name='course',
            name='syllabus',
        ),
        migrations.RemoveField(
            model_name='course',
            name='target_audience',
        ),
        migrations.AddField(
            model_name='course',
            name='affiliate_url',
            field=models.URLField(blank=True, null=True, verbose_name='Партнёрская ссылка'),
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='course',
            name='price_details',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация о цене'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован')], default=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновлёния'),
        ),
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(default='http://skillhub.ru', verbose_name='Ссылка на страницу курса'),
            preserve_default=False,
        ),
    ]
