# Generated by Django 3.1.1 on 2021-02-07 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровни сложности',
                'db_table': 'difficulty_level',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.difficultylevel', verbose_name='Уровень сложности'),
        ),
    ]
