# Generated by Django 3.2.9 on 2022-06-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='epc',
            field=models.FloatField(default=0, verbose_name='Средний зароботок с перехода'),
        ),
    ]
