# Generated by Django 3.2.2 on 2021-06-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_details',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация о цене'),
        ),
    ]
