# Generated by Django 3.2.6 on 2021-09-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210829_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_category',
            field=models.PositiveIntegerField(choices=[(0, 'Продолжительность отсутствует'), (1, 'Короткая продолжительность'), (2, 'Небольшая продолжительность'), (3, 'Средняя продолжительность'), (4, 'Значительная продолжительность'), (5, 'Высокая продолжительность')], default=3, verbose_name='Категория продолжительности'),
        ),
    ]
