# Generated by Django 3.2.8 on 2021-11-13 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_duration_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='government_support',
            field=models.BooleanField(default=False, verbose_name='Государственная программа дополнительного образования в сфере цифровой экономики'),
        ),
    ]
