# Generated by Django 3.1.6 on 2021-02-13 20:59

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_category_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=core.fields.AutoSlugField(populate_from='name', unique=True, verbose_name='Слаг'),
        ),
    ]
