# Generated by Django 3.2.9 on 2021-11-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211113_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_category',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Категория продолжительности'),
        ),
        migrations.AlterField(
            model_name='course',
            name='government_support',
            field=models.BooleanField(default=False, verbose_name='Гос. поддержка'),
        ),
    ]
