# Generated by Django 3.2.9 on 2022-08-11 19:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='extra_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Дополнительный текст'),
        ),
        migrations.AddField(
            model_name='category',
            name='extra_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительный заголовок'),
        ),
    ]
