# Generated by Django 3.2.9 on 2022-12-18 22:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20220904_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=ckeditor.fields.RichTextField(verbose_name='Название'),
        ),
    ]
