# Generated by Django 3.2.9 on 2022-03-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендуем'),
        ),
    ]
