# Generated by Django 3.2.9 on 2023-11-11 15:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
