# Generated by Django 3.2.9 on 2024-04-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20240407_1507'),
    ]

    operations = [
    ]
