# Generated by Django 3.2.9 on 2022-07-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='epc',
            field=models.FloatField(default=0, verbose_name='Средний зароботок с перехода'),
        ),
    ]
