# Generated by Django 3.2.9 on 2022-11-25 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
        ('schools', '0002_school_epc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='epc',
            field=models.FloatField(default=0, verbose_name='Средний заработок с перехода'),
        ),
        migrations.CreateModel(
            name='SchoolAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school', verbose_name='Школа')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.datasource', verbose_name='Источник данных')),
            ],
            options={
                'verbose_name': 'Псевдоним школы',
                'verbose_name_plural': 'Псевдонимы школ',
            },
        ),
    ]
