# Generated by Django 3.2.9 on 2021-11-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
    ]
