# Generated by Django 3.2.9 on 2021-11-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_school_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
    ]
