# Generated by Django 3.2.9 on 2022-11-25 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
        ('schools', '0004_alter_schoolalias_school'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolalias',
            unique_together={('school', 'source')},
        ),
    ]
