# Generated by Django 3.2.9 on 2022-11-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_schoolalias_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolalias',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Отключен'),
        ),
    ]
