# Generated by Django 3.2.9 on 2024-03-03 17:31

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_advantages_disadvantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=core.fields.AutoSlugField(populate_from='name', verbose_name='Слаг'),
        ),
    ]
