# Generated by Django 3.2.6 on 2021-09-06 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_school_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255, verbose_name='Источник отзыва')),
                ('url', models.URLField(verbose_name='Ссылка на отзыв')),
                ('published', models.DateField(verbose_name='Дата публикации отзыва')),
                ('advantages', models.TextField(blank=True, null=True, verbose_name='Положительная часть отзыва')),
                ('disadvantages', models.TextField(blank=True, null=True, verbose_name='Отрицательная часть отзыва')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Основной текст отзыва')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='schools.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
