# Generated by Django 3.2.9 on 2022-11-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text_sentiment',
            field=models.IntegerField(choices=[(2, 'Негативный'), (3, 'Нейтральный'), (4, 'Позитивный')], default=1, verbose_name='Тональность текста отзыва'),
        ),
    ]
