# Generated by Django 3.2.9 on 2022-11-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_text_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text_sentiment',
            field=models.IntegerField(choices=[(1, 'Неизвестен'), (2, 'Негативный'), (3, 'Нейтральный'), (4, 'Позитивный')], default=1, verbose_name='Тональность текста отзыва'),
        ),
    ]
